sudo: required

language: R

services:
  - docker

before_install:
  - docker build -t diegovalle/elcrimen-docker .

install: travis_wait 30 mvn install

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

branches:
  only:
    - master