sudo: required

language: R

services:
  - docker

install:
  - travis_wait 140 docker build -t diegovalle/elcrimen-docker .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

branches:
  only:
    - master