sudo: required

language: R

services:
  - docker

install:
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - docker build -t diegovalle/elcrimen-docker .
  # Killing background sleep loop
  - kill %1

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

branches:
  only:
    - master