version: 2
jobs:
  build:
    branches:
      only:
        - master
    working_directory: /app
    docker:
      - image: docker:17.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t diegovalle/elcrimen-docker .
          no_output_timeout: 1800
      - deploy:
          name: Deploy image to Docker Hub
          command: |
            /bin/sh docker_push