---
- hosts: all
  gather_facts: False

  tasks:
  - name: install python
    raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3 python3-setuptools)

- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600


  tasks:
    # Locales
    - name: install locales
      apt: name=locales state=latest

    - name: Spanish locale
      locale_gen: name=es_ES.UTF-8 state=present

    - name: English locale
      locale_gen: name=en_US.UTF-8 state=present

    - name: Update distro
      apt: upgrade=dist update_cache=yes

    - name: Creates .Rprofile with default repo
      lineinfile: dest=~/.Rprofile line='local({r <- getOption("repos");r["CRAN"] <- "https://mran.revolutionanalytics.com/snapshot/2021-10-20";options(repos = r)})' create=True
      become: yes
      become_user: rstudio

    - name: Clone repo new.crimenmexico
      git: repo=https://github.com/diegovalle/new.crimenmexico dest=~/new.crimenmexico force=yes
      become: yes
      become_user: rstudio

    - name: Refresh Font cache
      command: fc-cache -f -v
      
    - name: Install virtualenv
      command: pip3 install virtualenv 

    - name: Create the initial virtualenv
      command: virtualenv ~/.virtualenvs/crimenmexico/ -p python3 creates="~/.virtualenvs/crimenmexico/"
      become: yes
      become_user: rstudio

    - name: Install requirements.txt into virtualenv
      pip:
        requirements=~/new.crimenmexico/requirements.txt
        virtualenv=~/.virtualenvs/crimenmexico/
      become: yes
      become_user: rstudio

    - apt: name="{{ item }}" state=latest
      with_items:
        - libfreetype6
        - libfreetype6-dev
        - libfontconfig

    - name: Install sudo
      apt: pkg=sudo state=latest

    - name: Accept License
      shell: 'echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections'
    - apt: pkg=ttf-mscorefonts-installer

    - name: Update distro
      apt: upgrade=dist update_cache=yes
