---
- hosts: all
  gather_facts: False

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  - name: Install Python Packages
    apt: name="{{ item }}" state=latest
    with_items:
        - python-pip
        - python-virtualenv
        - python-dev
        - libffi-dev 
        - libssl-dev 
        - libxml2-dev 
        - libxslt1-dev 
        - libjpeg8-dev 
        - zlib1g-dev
  - name: pip utilities for https
    pip: name={{ item }} state=latest
    with_items:
      - urllib3

- hosts: all
  vars:
    nodejs_nodesource_pin_priority: 500
    r_repository:
      - type: deb
        url: "http://cran.rstudio.com/bin/linux/ubuntu  {{ ansible_distribution_release }}/"

  tasks:

    - name: apt-get update
      raw: apt-get update -qq

    # needed for installing hashlib
    - file: path=/usr/lib/python2.7/lib-dynload/_hashlib.x86_64-linux-gnu.so state=absent

    - name: Add R repository public key
      apt_key:
        id: E084DAB9
        keyserver: keyserver.ubuntu.com
        state: present
      tags:
        - r-repository-public-key

    - name: Add R repository
      apt_repository:
        repo: "{{ item.type }} {{ item.url }}"
        state: present
        update_cache: true
      with_items: "{{ r_repository }}"
      tags:
        - r-repository-add

    - name: Update distro
      apt: upgrade=dist update_cache=yes

    - name: Spanish locale
      locale_gen: name=es_ES.UTF-8 state=present

    - name: English locale
      locale_gen: name=en_US.UTF-8 state=present

    - name: Remove Packages
      apt: name="{{ item }}" state=absent
      with_items:
        - apache
        - samba
        - sendmail
        - bind9
        - ncsd
        - sasl
        - exim
        - ntp

    - name: Install Packages
      apt: name="{{ item }}" state=latest
      with_items:
        - git
        - r-base
        - r-base-dev
        - libv8-3.14-dev
        - curl
        - libreoffice
        - python-virtualenv
        - python-dev
        - libcurl4-openssl-dev
        - sqlite3
        - libxml2-dev
        - r-cran-xml
        - libgdal1-dev
        - libproj-dev
        - imagemagick
        - optipng
        - htop
        - gdal-bin
        - apt-transport-https
        - openssh-client
        - rsync
        - nano

    # ansible-playbook -i hosts playbook.yml --vault-password-file=password.txt --extra-vars "secrets=true"
    - name: Load secrets
      when: secrets is defined
      include_vars: secrets.yml
      no_log: true

    - name: Ensure .ssh directory exists.
      when: secrets is defined
      file:
        dest: "{{ key_file | dirname }}"
        mode: 0700
        state: directory

    # rsync -Pav -e 'ssh -i ~/.ssh/crimenmexico'  /root/new.crimenmexico crimenmexico@168.235.92.165:/home/crimenmexico
    - name: Install ssh key
      when: secrets is defined
      copy:
        content: "{{ ssh_key }}"
        dest: "{{ key_file }}"
        mode: 0600
      no_log: true

    - name: tell the host about servers it might want to ssh to
      when: secrets is defined
      known_hosts: path='/etc/ssh/ssh_known_hosts'
                   name='168.235.92.165'
                   key="{{ lookup('file', 'crimenmexico.pub') }}"

    - name: Creates .Rprofile with default repo
      lineinfile: dest=/root/.Rprofile line='local({r <- getOption("repos");r["CRAN"] <- "https://mran.revolutionanalytics.com/snapshot/2016-10-20";options(repos = r)})' create=True

    - name: Clone repo new.crimenmexico
      git: repo=https://github.com/diegovalle/new.crimenmexico dest=/root/new.crimenmexico force=yes

    - name: Install fonts
      command: find /root/new.crimenmexico/R/fonts/ -type f -name '*.ttf' -print -exec cp {} /usr/share/fonts/truetype/ \;

    - name: Refresh Font cache
      command: fc-cache -f -v

    - name: Creates tabula-java directory
      file: path=~/new.crimenmexico/downloader/tabula-java state=directory

    - name: download tabula-java
      get_url: url=https://github.com/tabulapdf/tabula-java/releases/download/tabula-0.9.0/tabula-0.9.0-SNAPSHOT-jar-with-dependencies.jar dest=~/new.crimenmexico/downloader/tabula-java

    - name: Create the initial virtualenv
      command: virtualenv ~/.virtualenvs/crimenmexico/ -p python2 creates="~/.virtualenvs/crimenmexico/"

    - name: Install requirements.txt into virtualenv
      pip:
        requirements=~/new.crimenmexico/requirements.txt
        virtualenv=~/.virtualenvs/crimenmexico/

    - name: Add R packages
      command: /usr/bin/Rscript --slave --no-save --no-restore-history -e "if (! ('{{item}}' %in% installed.packages()[,'Package'])) install.packages(pkgs='{{item}}')"
      with_items:
        - pacman
        - devtools
        - dplyr
        - ggplot2
        - rgeos
        - magrittr
        - RSQLite
        - zoo
        - lubridate
        - stringr
        - grid
        - Rttf2pt1
        - extrafont
        - useful
        - rgdal
        - maptools
        - gpclib
        - raster
        - scales
        - jsonlite
        - hash
        - RColorBrewer
        - compiler
        - data.table
        - mgcv
        - tidyr
        - future
        - XML
        - geojsonio
        - RJSONIO
        - spdep

    - apt_repository:
        repo: "{{item}}"
      register: multiverse_installed
      when: ansible_distribution == 'Ubuntu'
      with_items:
        - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
        - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
        - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
        - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'

    - apt: name="{{ item }}" state=latest
      with_items:
        - libfreetype6
        - libfreetype6-dev
        - libfontconfig

    - name: Accept License
      shell: 'echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections'
    - apt: pkg=ttf-mscorefonts-installer

    - name: Update distro
      apt: upgrade=dist update_cache=yes

    - name: Import fonts into R
      command: /usr/bin/Rscript --slave --no-save --no-restore-history -e "extrafont::font_import()"

    - name: Install github R packages
      command: /usr/bin/Rscript --slave --no-save --no-restore-history -e "devtools::install_github('{{item}}')"
      with_items:
        - diegovalle/mxmortalitydb
        - twitter/AnomalyDetection
        - diegovalle/mxmaps

    - name: Import the NodeSource GPG key into apt
      apt_key:
        id: 68576280
        url: "https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280"

    - name: Add NodeSource deb repository
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main'
        state: present

    - name: Add NodeSource deb-src repository
      apt_repository:
        repo: 'deb-src https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main'
        state: present

    - name: Add NodeSource repository preferences
      template:
        src: deb_nodesource_com_node.pref.2
        dest: /etc/apt/preferences.d/deb_nodesource_com_node.pref

    - name: Install Node.js
      apt:
        pkg:
          - nodejs
        state: installed
        update_cache: yes

    - name: Install phantomjs
      npm: name=phantomjs-prebuilt global=yes

    - name: Install casperjs
      npm:  name=casperjs global=yes

    - name: Install simplehttpserver
      npm:  name=simplehttpserver global=yes

    # Zopfli compression

    - name: Create temp directory for downloading zopfli
      command: mktemp -d /tmp/zopfli.XXXXXX
      register: mktemp_output
    
    - name: check installed
      command: /usr/local/bin/zopfli -h
      register: result
      ignore_errors: True
      changed_when: False

    - name: Clone zopfli repo
      git: repo=https://github.com/google/zopfli dest={{ mktemp_output.stdout }} force=yes
      when: result.rc != 0

    - name: make
      command: make -j{{ ansible_processor_cores }} chdir={{ mktemp_output.stdout }}
      when: result.rc != 0

    - name: install
      shell: if [ -f {{ mktemp_output.stdout }}/zopfli ]; then cp {{ mktemp_output.stdout }}/zopfli /usr/local/bin/zopfli; fi
      when: result.rc != 0

